agatka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', include('better_admin.urls')),
    path('', include('homepage.urls')),
    path('about-me', include('about_me.urls')),
    path('contact', include('contact.urls')),
    path('image', include('images.urls')),
    path('portfolio', include('portfolio.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#handler404 = 'homepage.views.view_404'

better_admin/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    path('', views.Better_admin, name="better_admin"),
    path('add_images/', views.AddImages),
    path('add_images/get_groups/', views.GetGroups),
    path('add_images/new_group/', views.NewGroup),
    path('add_images/new_image/', views.NewImage),
    path('image_compress_all/', views.CompressAllImages),
    path('image_compress/', views.CompressImages),
    path('panel/', admin.site.urls),
    path('login/', views.Login, name="login"),
]

better_admin/models.py
from django.db import models

# Create your models here.

images/forms.py
import django.forms as forms
from .models import Category, Group, Image
from datetime import datetime 

class GroupForm(forms.ModelForm):
    visible_name = forms.CharField(
        widget=forms.TextInput(attrs={
                'placeholder': 'Nazwa grupy zdjęć',
                'class' : "form-control",
                'autocomplete':'off'
            }),
        label = "Nazwa"
    )
    friendly_link = forms.CharField(
        widget=forms.TextInput(attrs={
                'placeholder': 'Przyjazny link',
                'class' : "form-control",
                'autocomplete':'off'
            }),
        label = "Link"
    )
    display = forms.BooleanField(
        widget=forms.CheckboxInput(),
        label = "Grupa widoczna",
        initial=True,
        required=False
    )
    relase_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={
                'class' : "form-control",
                'autocomplete':'off'
            }),
        initial = datetime.now,
        label = "Data wyświetlenia"
    )
    background_image = forms.FileField(
        widget=forms.FileInput(attrs={
                'class' : "form-control",
                'autocomplete':'off',
                "accept":"image/*"
            }),
        label = "Wybierz zdjęcia"
    )
    cat = forms.DecimalField(
        widget=forms.HiddenInput(),
        label = False
    )
    category = forms.Field(
        widget=forms.HiddenInput(),
        required = False,
        label = False
    )

    class Meta:
        model = Group
        fields = ('visible_name', 'friendly_link', 'display', 'relase_date', 'background_image', 'category')
    
    def clean_friendly_link(self, *args, **kwargs):
        friendly_link = self.cleaned_data["friendly_link"]
        friendly_link = friendly_link.replace(" ", "-")
        category = Category.objects.filter(id=self.data.get("cat"))

        try:
            groups = Group.objects.filter(category=category, friendly_link=friendly_link)
            if groups.count != 0:
                print("Taki link już istnieje w tej kategorii") 
                raise forms.ValidationError("Taki link już istnieje w tej kategorii") 

        except:
            pass
        return friendly_link

    def clean_category(self, *args, **kwargs):
        category = Category.objects.filter(id=int(self.data.get("cat")))
        return category[0]



class ImageForm(forms.ModelForm):
    image = forms.FileField(
        widget=forms.FileInput(attrs={
                'class' : "form-control",
                'autocomplete':'off',
                "accept":"image/*"
            }),
        label = "Wybierz zdjęcia"
    )

    cat = forms.DecimalField(
        widget=forms.HiddenInput(),
        label = False
    )
    grp = forms.DecimalField(
        widget=forms.HiddenInput(),
        label = False
    )
    category = forms.Field(
        widget=forms.HiddenInput(),
        required = False,
        label = False
    )
    group = forms.Field(
        widget=forms.HiddenInput(),
        required = False,
        label = False
    )
    friendly_link = forms.CharField(
        widget=forms.HiddenInput(),
        required = False,
    )

    visible_name = forms.CharField(
        widget=forms.HiddenInput(),
        required = False,
    )
    display = forms.BooleanField(
        widget=forms.HiddenInput(),
        initial=True,
    )
    relase_date = forms.DateTimeField(
        widget=forms.HiddenInput(),
        initial = datetime.now,
    )

    class Meta:
        model = Image
        fields = ('image', 'friendly_link', 'visible_name', 'display', 'relase_date', "category", "group")


    def clean_category(self, *args, **kwargs):
        category = Category.objects.filter(id=int(self.data["cat"]))
        return category[0]

    def clean_group(self, *args, **kwargs):
        group = Group.objects.filter(id=int(self.data["grp"]))
        return group[0]
    
    def clean_friendly_link(self, *args, **kwargs):
        friendly_link = self.data.get("friendly_link")
        if friendly_link == "":
            friendly_link = str(self.cleaned_data.get("image").name.split(".")[0])
        friendly_link = friendly_link.replace(" ", "_")
        group = Group.objects.filter(id=self.data.get("grp"))[0]
        
        last_i = ""
        for i in range(99999):
            print("friendly_link:'",friendly_link+last_i,"'")
            image = Image.objects.filter(group=group, friendly_link=(friendly_link+last_i))
            if image.count() == 0:
                return friendly_link
            last_i = str(i)

    def clean_visible_name(self, *args, **kwargs):
        visible_name = self.cleaned_data.get("friendly_link")
        return visible_name


class ImageForm2(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('visible_name', 'friendly_link', 'display', 'relase_date', 'image', 'category', 'group')
        widgets = {
            'image': forms.ClearableFileInput(attrs={'multiple': True}),
        }

better_admin/views.py
from agatka.useful import *
import images.models as imagesModels
import images.forms as imagesForms
import django.forms as modelsformset_factory
from django.core.files.storage import FileSystemStorage
from django.core.files.uploadedfile import SimpleUploadedFile
        
from django.views.decorators.csrf import csrf_exempt

def Better_admin(request):
    if not request.user.is_superuser:
        return Login(request)
    else:
        ctx = set_navname("admin", base_context(request))
        return render(request, "admin.html", ctx)

def Login(request):
    return redirect('/admin/panel/login/?next=/admin/')

def CompressAllImages(request):
    for i in imagesModels.Image.objects.all():
        try:
            i.save()
        except: pass
    for i in imagesModels.Group.objects.all():
        try:
            i.save()
        except: pass
    for i in imagesModels.Category.objects.all():
        try:
            i.save()
        except: pass
    return redirect('/admin/')

def CompressImages(request):
    from django.db.models import Q   
    for i in imagesModels.Image.objects.filter(
        Q(reducted_image='')|Q(reducted_image=None)
    ):
        try:
            i.save()
        except: pass
    for i in imagesModels.Group.objects.filter(
        Q(reducted_image='')|Q(reducted_image=None)
    ):
        try:
            i.save()
        except: pass
    return redirect('/admin/')

def AddImages(request):
    if not request.user.is_superuser:
        return Login(request)
    else:
        ctx = set_navname("add_images", base_context(request))
        ctx["categories"] = imagesForms.Category.objects.all()
    
        ctx["categories_select"] = "none"
        ctx["groups_select"] = "none"
        if request.method == "POST":

            ctx["categories_select"] = request.POST.get("categories_select", "none")
            ctx["groups_select"] = request.POST.get("groups_select", "none")
            template = get_template("add_images/main.html")
            content = template.render(ctx)
            return JsonResponse({"html":content})
        return render(request, "add_images/main.html", ctx)

@csrf_exempt
def GetGroups(request):
    if request.method == 'GET':
        category = request.GET["category"]
        cat = imagesForms.Category.objects.filter(id=category)[0]
        grp = imagesForms.Group.objects.filter(category=cat)
        ctx = {"groups":grp}
        ctx["groups_select"] = "none"
        if request.method == "POST":
            ctx["groups_select"] = request.POST.get("groups_select", "none")

        ctx["img_form"] = imagesForms.ImageForm2()
        template = get_template("add_images/get_groups.html")
        content = template.render(ctx)
        return JsonResponse({"html":content})

@csrf_exempt
def NewImage(request):
    if request.user.is_superuser:
        form = imagesForms.ImageForm()
        ctx = {}
        if request.method == 'POST':
            form = imagesForms.ImageForm(data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "Dodano zdjęcie")
                return JsonResponse({"success":True})
            else:
                messages.error(request, "Nie udało się dodać zdjęcia, spróbuj jeszcze raz lub skontaktuj się z deweloperem strony")
                try:
                    form.save()
                except Exception as e:
                    messages.error(request, "Error" + str(e))

            
        ctx['form'] = form
        template = get_template("add_images/new_image.html")
        content = template.render(ctx)
        return JsonResponse({"html":content})

@csrf_exempt
def NewGroup(request):
    if request.user.is_superuser:
        form = imagesForms.GroupForm()
        ctx = {}
        if request.method == 'POST':
            form = imagesForms.GroupForm(data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "Stworzono nową grupe")
                return JsonResponse({"success":True})
            else:
                messages.error(request, "Nie udało się utworzyć grupy, spróbuj jeszcze raz lub skontaktuj się z deweloperem strony")
                try:
                    form.save()
                except Exception as e:
                    messages.error(request, "Error" + str(e))
            
        ctx['form'] = form
        template_link ="add_images/new_group.html"
        template = get_template(template_link )
        content = template.render(ctx)
        return JsonResponse({"html":content})

better_admin/templates/add_images/get_groups.html
<div class="input-group mt-3 px-1">
    <div class="input-group-prepend">
        <label class="input-group-text" for="groups_select">Grupa</label>
    </div>
    <select class="custom-select" id="groups_select"  name="groups_select" onchange="GetGroup(this)">
        {% load converts  %}
        <option value="none"  {% if groups_select == "none" %} selected {% endif %}>Wybierz grupe</option>
        <option value="add_new"  {% if groups_select == "add_new" %} selected {% endif %}>Dodaj nową</option>
        {% for i in groups %}
            <option value="{{ i.id }}" {% if groups_select|to_int == i.id %} selected {% endif %}>"{{ i.visible_name }}"</option>
        {% endfor %}
    </select>

    <div id="new_group" class="input-group card text-white bg-secondary" style="display: none;">
        <!-- nowa grupa -->
    </div>

    <div class="input-group" id="images_holder" style="display: none;">
        <div class="input-group" id="images">
        </div>
        <div class="input-group mt-3">
            <buttn class="btn btn-light btn-lg p-2 col" onclick="AddImageForm(document.getElementById('images'))">Dodaj nowy formularz do zdjęcia</buttn>
        </div>
    </div>

<script>
    function GetGroup(element) {
        var value = element.value;
        $('#new_group').html("")
        $('#new_group').css("display", "none")
        $('#images_holder').css("display", "none")
        $('#files').val('')
        $('#images').html('')
        if (value != "none")
        {
            if (value == "add_new")
            {
                $('#new_group').css("display", "block")

                data = {
                }

                $.ajax({
                    type: 'GET',
                    url: '/admin/add_images/new_group',
                    data: data,
                    success: function (data) {
                        $('#new_group').html(data.html)
                        $('#new_group').find("#id_cat").val($("#categories_select").val())
                        getMesseges()
                    },
                    error: function () {
                        getMesseges()
                    }
                });
            }
            else{
                $('#images_holder').css("display", "block")
            }
        }
    }
    GetGroup(document.getElementById("groups_select"))

    var id = 0

    function AddImageForm(element) {
        $.ajax({
            type: 'GET',
            url: '/admin/add_images/new_image',
            data: data,
            success: function (data) {
                html = $(data.html);
                $(html).find("#id_cat").val($("#categories_select").val());
                $(html).find("#id_grp").val($("#groups_select").val());
                $('#images').append(html);
            }
        });
    }
    GetGroup(document.getElementById("groups_select"))

    

    function SaveImages() {
        
        $("#images form").each(function( index ){
            temp_this = $(this)
            if ($(this).find("#id_image").val() != "")
                $(this).ajaxSubmit({
                    url: '/admin/add_images/new_image/',
                    type: 'POST',
                    success: function (data) {
                        $(temp_this).html(data.html)
                        if (data.success == true){
                            $(temp_this).remove()
                        }
                        getMesseges()
                    },
                    error: function () {
                        getMesseges()
                    }
                })
            else 
                $(temp_this).remove()
        })
    }
</script>
</div>

better_admin/templates/add_images/main.html
{% extends "base.html" %}

<!-- {% block title %}{{ section.title }}{% endblock %} -->

{% block additional_include %}
    {% load static %}
{% endblock %}
{% block content %}

<div id="container">
<section id="pageContent">
    <form id="main_form" enctype="multipart/form-data" class="container d-flex justify-content-center">
        <div class="p-2 d-flex flex-column w-75" name="imageform" id="imageform">
            {% csrf_token %}
            {% load converts %}

            <div class="input-group card text-white bg-secondary mb-3">
                <!-- kategoria -->
                <div class="input-group">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="categories_select">Kategoria</label>
                    </div>
                    <select class="custom-select" id="categories_select" name="categories_select" onchange="GetCategory(this)">
                        <option value="none" {% if categories_select == "none" %} selected {% endif %}>Wybierz kategorie</option>
                        {% for i in categories %}
                            <option value="{{ i.id }}" {% if categories_select|to_int == i.id %} selected {% endif %}>{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div id="group" class="input-group card text-white bg-secondary" style="display: none;">
                    <!-- group -->
                </div>
            </div>

            <!-- submit -->
            <div class="input-group">
                <buttn class="btn btn-secondary btn-lg p-2 col" onclick="Submit()">Dodaj</buttn>
                <div class="col-1"></div>
                <a href="admin/" class="col p-0 m-0"><div class="btn btn-secondary btn-lg p-2 w-100">wróć</div></a>
            </div>
        </div>

        
    <script>
        function GetCategory(element, to="") {
            var value = element.value;
            $('#group').html("")
            $('#group').css("display", "none")
            if (value != "none")
            {
                $('#group').css("display", "block")
                data = {
                    "category" : value,
                    "groups_select" :"{{groups_select}}",
                }

                $.ajax({
                    type: 'GET',
                    url: '/admin/add_images/get_groups',
                    data: data,
                    success: function (data) {
                        $('#group').html(data.html)
                    }
                });
            }
        }
        GetCategory(document.getElementById("categories_select"))

        function Submit(){
            if(typeof(Submit_new_group) === "function"){
                Submit_new_group()
            } else if(typeof(SaveImages) === "function"){
                SaveImages()
            } 
        }
    </script>
  </form>
  <script>
    function reloadPage(){
        location.reload(); 
    }
  </script>
</section>
</div>
{% endblock %}

better_admin/templates/add_images/new_group.html
<form id="add_new_group"  class="px-2 d-flex flex-column w-100 form" name="add_new_group" method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    
{% load converts  %}
    {% for field in form.visible_fields %}
        <div class="input-group mt-3">
            {% for error in field.errors %}
            <div class="input-group mb-1">
                <div class="form-control alert-danger">{{ error|escape }}
                </div>
            </div>
            {% endfor %}
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text pt-0 pb-0">{{field.label}}</div>
                </div>
                {% if field == form.display %}
                    <div class="form-control">{{field}}</div>
                {% else %}
                    {{field}}
                {% endif %}
                
            </div>
        </div>
    {% endfor %}
    
    {% for field in form.hidden_fields  %}
            {{field}}
    {% endfor %}
    
{% if pure_html %}
    <input type="hidden" name="pure_html" value="{{pure_html}}"/>
    <input type="submit" value="ok"/>
{% endif %}
</form>
<script>
    function Submit_new_group(){

        $("#add_new_group").ajaxSubmit({
            url: '/admin/add_images/new_group/',
            type: 'POST',
            success: function (data) {
                $('#add_new_group').html("");
                html = $(data.html).filter("#add_new_group").html()
                $('#add_new_group').html(html)
                $('#add_new_group').filter("#id_cat").val($("#categories_select").val())
                if (data.success == true){
                    // val = $("#categories_select").val()
                    // $("#categories_select").val("none")
                    // console.log($("#categories_select").val());
                    // console.log(val);
                    // $("#categories_select").val(val)
                    // GetCategory(document.getElementById("categories_select"), to=val)
                    location.reload()
                }
                getMesseges()
            },
            error: function () {
                getMesseges()
            }
        })
    }
</script>

better_admin/templates/add_images/new_image.html
<form id="add_new_image"  class="px-2 d-flex flex-column w-100 form" name="add_new_group" method="POST"  enctype="multipart/form-data">
    {% for field in form.visible_fields %}
        <div class="input-group mt-3">
            <div class="input-group-prepend">
                <div class="input-group-text pt-0 pb-0">{{field.label }}</div>
            </div>
            {% if field == form.display %}
            <div class="form-control">{{field}}</div>
            {% else %}
                {{field}}
            {% endif %}
        </div>
    {% endfor %}
    
    {% for field in form.hidden_fields  %}
        {{field}}
    {% endfor %}
</form>